version: '2'

services:

  elasticsearch:
    build:
      context: ./elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: ./elk/logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/logstash/config/:/usr/share/logstash/config/:ro
    ports:
      - "5000:5000"
      - "5959:5959"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: ./elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  jupyter: 
    image: jupyter/tensorflow-notebook
    container_name: jupyter
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ../python-basic/:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=""
    networks: 
      - elk

networks:

  elk:
    driver: bridge
